version: "3.8"

services:
  # -- Gateway service --
  gateway:
    build:
      context: ./services/gateway
      dockerfile: Dockerfile
    container_name: instagram-gateway
    ports:
      - 80:80
    depends_on:
      - auth-service
      - gateway-service
    networks:
      - instagram-network
    restart: unless-stopped

  # -- Auth service --
  auth-service:
    build:
      context: .
      dockerfile: ./services/auth-service/Dockerfile # explicitly specify Dockerfile path (since context is root)
    container_name: auth-service
    depends_on:
      - rabbitmq
    environment:
      - NODE_ENV=development
      - PORT=5000
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}
      - FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY}
    volumes:
      - ./services/auth-service:/app/services/auth-service # for hot reload in auth-service/
      - ./packages:/app/packages # for hot reload in packages/
      - /app/services/auth-service/node_modules
      - /app/packages/shared/node_modules
    ports:
      - 5000:5000
    networks:
      - instagram-network
    restart: unless-stopped

  # -- Profile service --
  profile-service:
    build:
      context: .
      dockerfile: ./services/profile-service/Dockerfile # explicitly specify Dockerfile path (since context is root)
    container_name: profile-service
    environment:
      - NODE_ENV=development
      - PORT=6000
    volumes:
      - ./services/profile-service:/app/services/profile-service # for hot reload in profile-service/
      - ./packages:/app/packages # for hot reload in packages/
      - /app/services/profile-service/node_modules
      - /app/packages/shared/node_modules
    ports:
      - 6000:6000
    depends_on:
      - rabbitmq
    networks:
      - instagram-network
    restart: unless-stopped

  # -- RabbitMQ service --
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672 # UI port
    networks:
      - instagram-network
    restart: unless-stopped
  gateway-service:
    build:
      context: .
      dockerfile: ./services/gateway-service/Dockerfile # explicitly specify Dockerfile path (since context is root)
    container_name: gateway-service
    environment:
      - NODE_ENV=development
      - PORT=4000
    ports:
      - 4000:4000
    depends_on: # Since requests are routed to these services
      - auth-service
      - profile-service
    networks:
      - instagram-network
    restart: unless-stopped

networks:
  instagram-network:
    driver: bridge
