apiVersion: v1
kind: Service
metadata:
  name: profile-service
  namespace: instagram-backend
spec:
  selector:
    app: profile
  ports:
    - protocol: TCP
      port: 6000
      targetPort: 6000
  type: ClusterIP
